# This file was generated by GoReleaser. DO NOT EDIT.
cask "kyrc" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "b7c6f877bafb0e014a7c50a9901c955d16955426638d4c8b9609e05e148cbd67"
      url "https://github.com/abh1nav9/kyrc/releases/download/v#{version}/kyrc_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f89d58bd57379ae8f0ab68a3f98775e72acd44305b171999735022f5e604b66b"
      url "https://github.com/abh1nav9/kyrc/releases/download/v#{version}/kyrc_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8ba06045b5f2bf8f2d8980ef72a7e7798f44a9313d50d3e3323921876aa5fd41"
      url "https://github.com/abh1nav9/kyrc/releases/download/v#{version}/kyrc_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e08ef17cbafe5a56911db29bd696609684cb7ea45bb7ec9b5968ff308a33adc5"
      url "https://github.com/abh1nav9/kyrc/releases/download/v#{version}/kyrc_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kyrc"
  desc "A fast, offline, keyboard-only typing test for your terminal."
  homepage "https://github.com/abh1nav9/kyrc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kyrc"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/kyrc"]
    end
  end

  # No zap stanza required

end
