# This file was generated by GoReleaser. DO NOT EDIT.
cask "kyrc" do
  version "0.1.8"

  on_macos do
    on_intel do
      sha256 "7de39726cb86f1fb35d441b90354d58ed2f9baac1b336a4e62f662dc8903c15e"
      url "https://github.com/abh1nav9/kyrc/releases/download/v#{version}/kyrc_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2203597fda4273e2ba5b176d4e3a96516e623310720f9133251ca140ca609cec"
      url "https://github.com/abh1nav9/kyrc/releases/download/v#{version}/kyrc_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5b194778a8197595d544ae6ae48320bf1b5e7748048e556720ed92be67a22f91"
      url "https://github.com/abh1nav9/kyrc/releases/download/v#{version}/kyrc_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5f23d2b321dac3cb723fe65f62820d1c7516373e0664909522a70f5edb2f304b"
      url "https://github.com/abh1nav9/kyrc/releases/download/v#{version}/kyrc_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kyrc"
  desc "A fast, offline, keyboard-only typing test for your terminal."
  homepage "https://github.com/abh1nav9/kyrc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kyrc"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/kyrc"]
    end
  end

  # No zap stanza required

end
