# This file was generated by GoReleaser. DO NOT EDIT.
cask "kyrc" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "2f56b47a654ea10eb3d9a7403b726b9edc7c9b0b0b1ddd354f7fcc262c4b8a99"
      url "https://github.com/abh1nav9/kyrc/releases/download/v#{version}/kyrc_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "373fe37a90e4e427b4a7d4e9a837b6f4d3b0b89af6110de9992fbbb899b1f46c"
      url "https://github.com/abh1nav9/kyrc/releases/download/v#{version}/kyrc_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3da6058cd6670659f3a8042578c10a8fa4b9ddd04d25ec578da74564d2149188"
      url "https://github.com/abh1nav9/kyrc/releases/download/v#{version}/kyrc_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e0d87fae3b5333dd621e0dfcd0461fc8abd152d7ea1776282a82e9f9b6abcc54"
      url "https://github.com/abh1nav9/kyrc/releases/download/v#{version}/kyrc_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kyrc"
  desc "A fast, offline, keyboard-only typing test for your terminal."
  homepage "https://github.com/abh1nav9/kyrc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kyrc"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/kyrc"]
    end
  end

  # No zap stanza required

end
